title: "Notes of zf2timo"
description: "A site creted by Spress"
logo: "spresso-logo.png"

# Your site's domain. E.g: http://yoursite.com
url: ""

parsedown_actived: true

# Comments in posts
comments:
    enabled: false
    disqus_shortname: ""

# Information about author
author:
    name: "Timo Tewes"

    # Social networks
    twitter: "zf2timo"
    github: "https://github.com/zf2timo"

# Collections
collections:
  posts:
    output: true

  projects:
    output: false

# RSS feed
feed:
    max_item: 10

# Facebook Open Graph
#open_graph:
#    locale: "en_US"

# Code highlight for <pre> and <code> tags
# Powered by http://highlightjs.org/
code_highlight: true

# Site validation
#google_verify:
#bing_verify:

# Page menus
top_menu:
    - { name: Home, url: "/" }

bottom_menu:
#    - { name: "Go to Spresso theme web", url: "https://github.com/yosymfony/Spress-theme-spresso" }
